# Generated by Django 4.1.2 on 2023-01-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0002_delete_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(null=True)),
                ('nama', models.CharField(max_length=500)),
                ('alamat', models.CharField(max_length=500)),
                ('jam_buka', models.CharField(max_length=500)),
                ('deskripsi', models.TextField(null=True)),
                ('gambar', models.CharField(max_length=500)),
            ],
        ),
    ]
