# Generated by Django 4.1.2 on 2023-01-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpi',
            name='deskripsi',
        ),
    ]
